// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReciboDeMercancia.Infrastructure.Data;

#nullable disable

namespace ReciboDeMercancia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624232025_NuevoEsquema")]
    partial class NuevoEsquema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Arribo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenedor")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Contenedor")
                        .IsUnique();

                    b.ToTable("arribos", (string)null);
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.ArriboDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArriboId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("PO")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SkuProducto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArriboId");

                    b.HasIndex("SkuProducto");

                    b.ToTable("arribos_detalle", (string)null);
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArriboDetalleId")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaFoto")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<string>("SkuProducto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoIncidencia")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArriboDetalleId");

                    b.HasIndex("SkuProducto");

                    b.ToTable("incidencias", (string)null);
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("operadores", (string)null);
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Producto", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("AltoProducto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AnchoProducto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("LargoProducto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("Upc")
                        .HasColumnType("bigint");

                    b.HasKey("Sku");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Recepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArriboId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaYHoraLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaYHoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IncidenciaId")
                        .HasColumnType("int");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArriboId");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("OperadorId");

                    b.ToTable("recepciones", (string)null);
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.ArriboDetalle", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Arribo", "Arribo")
                        .WithMany("Detalles")
                        .HasForeignKey("ArriboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("SkuProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arribo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Incidencia", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.ArriboDetalle", "ArriboDetalle")
                        .WithMany()
                        .HasForeignKey("ArriboDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("SkuProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArriboDetalle");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Recepcion", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Arribo", "Arribo")
                        .WithMany()
                        .HasForeignKey("ArriboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Incidencia", "Incidencia")
                        .WithMany()
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arribo");

                    b.Navigation("Incidencia");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Arribo", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
