// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReciboDeMercancia.Infrastructure.Data;

#nullable disable

namespace ReciboDeMercancia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Contenedor", b =>
                {
                    b.Property<string>("NumeroContenedor")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("NumeroContenedor");

                    b.ToTable("Contenedores");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.EntradaDeImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroContenedor")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OrdenCompra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NumeroContenedor");

                    b.ToTable("EntradasDeImportacion");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.EntradaDeImportacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("EntradaDeImportacionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntradaDeImportacionId");

                    b.HasIndex("ProductId");

                    b.ToTable("EntradasDeImportacionDetalles");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadAfectada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecepcionId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Operadores");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.OrdenDeCompra", b =>
                {
                    b.Property<string>("NumeroDeOrden")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroContenedor")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("NumeroDeOrden");

                    b.HasIndex("NumeroContenedor");

                    b.ToTable("OrdenesDeCompra");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.OrdenDeCompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroDeOrden")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDeOrden");

                    b.HasIndex("ProductId");

                    b.ToTable("OrdenesDeCompraDetalles");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AltoProducto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AnchoProducto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("LargoProducto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Upc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Recepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroContenedor")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("OperadorQCId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroContenedor")
                        .IsUnique();

                    b.HasIndex("OperadorQCId");

                    b.ToTable("Recepciones");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.RecepcionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadEsperada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CantidadRecibida")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("PrimeraCajaValidada")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecepcionId");

                    b.ToTable("RecepcionDetalles");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.RecepcionOperador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("RecepcionId");

                    b.ToTable("RecepcionOperadores");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.ValidacionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AltoReal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AnchoReal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Aprobada")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("LargoReal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PesoEsperado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PesoReal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RecepcionDetalleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionDetalleId")
                        .IsUnique();

                    b.ToTable("ValidacionesCaja");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.EntradaDeImportacion", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Contenedor", "Contenedor")
                        .WithMany()
                        .HasForeignKey("NumeroContenedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contenedor");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.EntradaDeImportacionDetalle", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.EntradaDeImportacion", "EntradaDeImportacion")
                        .WithMany("Detalles")
                        .HasForeignKey("EntradaDeImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntradaDeImportacion");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Incidencia", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Recepcion", "Recepcion")
                        .WithMany("Incidencias")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.OrdenDeCompra", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Contenedor", "Contenedor")
                        .WithMany("OrdenesDeCompra")
                        .HasForeignKey("NumeroContenedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contenedor");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.OrdenDeCompraDetalle", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.OrdenDeCompra", "OrdenDeCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("NumeroDeOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenDeCompra");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Recepcion", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Contenedor", "Contenedor")
                        .WithOne("Recepcion")
                        .HasForeignKey("ReciboDeMercancia.Domain.Entities.Recepcion", "NumeroContenedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Operador", "OperadorQC")
                        .WithMany()
                        .HasForeignKey("OperadorQCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contenedor");

                    b.Navigation("OperadorQC");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.RecepcionDetalle", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Recepcion", "Recepcion")
                        .WithMany("Detalles")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.RecepcionOperador", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReciboDeMercancia.Domain.Entities.Recepcion", "Recepcion")
                        .WithMany("Operadores")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.ValidacionCaja", b =>
                {
                    b.HasOne("ReciboDeMercancia.Domain.Entities.RecepcionDetalle", "RecepcionDetalle")
                        .WithOne("ValidacionCaja")
                        .HasForeignKey("ReciboDeMercancia.Domain.Entities.ValidacionCaja", "RecepcionDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecepcionDetalle");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Contenedor", b =>
                {
                    b.Navigation("OrdenesDeCompra");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.EntradaDeImportacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.OrdenDeCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.Recepcion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Incidencias");

                    b.Navigation("Operadores");
                });

            modelBuilder.Entity("ReciboDeMercancia.Domain.Entities.RecepcionDetalle", b =>
                {
                    b.Navigation("ValidacionCaja");
                });
#pragma warning restore 612, 618
        }
    }
}
